name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
        
    - name: Cache UPX
      uses: actions/cache@v3
      with:
        path: /usr/bin/upx
        key: ${{ runner.os }}-upx-4.2.2
        
    - name: Install UPX
      run: |
        if ! command -v upx &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y upx
        fi
        
    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/video_compressor.exe
          build/video_compressor
          build/video_compressor_mac
          build/upx/video_compressor-mini.exe
          build/upx/video_compressor-mini
          build/upx/video_compressor_mac-mini
        draft: false
        prerelease: false
        generate_release_notes: false
        name: "Video Compressor ${{ github.ref_name }}"
        body: ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}